#!/bin/sh

set -e

BLUE='\033[1;34m'
GREEN='\033[1;32m'
RED='\033[1;31m'
NC='\033[0m' # No Color

echo ""
echo "${BLUE}-------------------------------------${NC}"
echo "${BLUE}Commit Message Checks${NC}"
echo "${BLUE}-------------------------------------${NC}"

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
    echo "${RED}❌ Error: Aborting commit, your commit message do not adhere to the guidelines${NC}" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,100}$"; then
    echo "${RED}❌ Error: Aborting commit, commit messages cannot contain more than 100 characters${NC}" >&2
    exit 1
fi

echo "${GREEN}✔ Commit message checks passed${NC}"
echo ""
