#!/bin/sh

set -e

# Colors (ANSI)
RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m' # No Color

# Get staged Rust files
STAGED_RS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rs$' || true)

echo "${BLUE}-------------------------------------${NC}"
echo "${BLUE}Pre-commit Checks${NC}"
echo "${BLUE}-------------------------------------${NC}"

if [ -n "$STAGED_RS_FILES" ]; then
    echo "${YELLOW}Staged Rust files:${NC}"

    echo "$STAGED_RS_FILES" | while IFS= read -r file; do
    printf "  %b- %b%b\n" "$YELLOW" "$file" "$NC"
done

echo ""
echo "${BLUE}Running rustfmt on staged files...${NC}"
echo "$STAGED_RS_FILES" | xargs rustfmt

  # Re-stage formatted files
  echo "$STAGED_RS_FILES" | xargs git add
  echo "${GREEN}✔ Format successfull${NC}"
else
    echo "${YELLOW}No staged Rust files found${NC}"
fi

echo ""
echo "${BLUE}Running Clippy on entire crate:${NC}"
echo "  ${YELLOW}Targets:${NC} all-targets"
echo "  ${YELLOW}Features:${NC} all-features"
echo ""

cargo clippy --all-targets --all-features -- -D warnings
echo "${GREEN}✔ Lint successfull${NC}"

echo ""
echo "${GREEN}✔ Pre-commit checks passed${NC}"
